# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 10e1e0287dcc70b595fa043c513b3ebea327d540bcaa7c063377f6286626e31a874fa606899ea1d8b68389cc3bcd234a65fc8d82c39e969b2ecf320e7bfe0106

test:
  secret_key_base: 5a48059b1ded38e1d43e9ef36d4f1587e4c8901f0928dc87a6580545914a1ce45a8be00bd68991cf905bd952d6365fbfc1aa22c8e5e1d23a8e4fcc01ee64dba8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
